// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXJVPGovV7KnQuM5aeMkGPAE_5PPzdLg',
    appId: '1:337158725624:web:b29add9ef42db4d9f8c00d',
    messagingSenderId: '337158725624',
    projectId: 'hack4change-6bc07',
    authDomain: 'hack4change-6bc07.firebaseapp.com',
    storageBucket: 'hack4change-6bc07.appspot.com',
    measurementId: 'G-0F9BQ181YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNETw3lbwPoH0T8kRpSyQMBBYeLEqPrt4',
    appId: '1:337158725624:android:6d9954a05e4bd3a9f8c00d',
    messagingSenderId: '337158725624',
    projectId: 'hack4change-6bc07',
    storageBucket: 'hack4change-6bc07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXDM42Vybt61ZIce5h3lHNZISBYYL024Q',
    appId: '1:337158725624:ios:c139157576484bf5f8c00d',
    messagingSenderId: '337158725624',
    projectId: 'hack4change-6bc07',
    storageBucket: 'hack4change-6bc07.appspot.com',
    androidClientId: '337158725624-l9ves5thh6dij2oeh51kse9oukthlbiq.apps.googleusercontent.com',
    iosClientId: '337158725624-rium151s35ho68h98gjrj39qq0ld57ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXDM42Vybt61ZIce5h3lHNZISBYYL024Q',
    appId: '1:337158725624:ios:ae645c9aa24333cff8c00d',
    messagingSenderId: '337158725624',
    projectId: 'hack4change-6bc07',
    storageBucket: 'hack4change-6bc07.appspot.com',
    androidClientId: '337158725624-l9ves5thh6dij2oeh51kse9oukthlbiq.apps.googleusercontent.com',
    iosClientId: '337158725624-1o09pan8u8944sagru752thm27hq0c9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
